yt-dlp `
--downloader aria2c `
--downloader-args "--continue --max-concurrent-downloads=16 --max-connection-per-server=16 --split=16 --min-split-size=5M" `
--force-ipv4 `
--keep-video `
--cookies-from-browser $(get-content ./__browser.txt) `
--ignore-errors `
--no-continue `
--no-overwrites `
--add-metadata `
--write-description `
--write-info-json `
--write-annotations `
--write-thumbnail `
--embed-thumbnail `
--all-subs `
--embed-subs `
--get-comments `
--check-formats `
--concurrent-fragments $(get-content ./__concurrent-fragments-media.txt) `
--output $(get-content ./__output-format.txt) `
--throttled-rate 100K `
$args 2>&1
